import type { Metadata } from 'next'
import { type JSX } from 'react'
import { GoogleApi } from '~/components/google-api'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang='en'>
      <body>{children}</body>
      <GoogleApi />
    </html>
  )
}

export default RootLayout
