import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import '@mantine/dropzone/styles.css'
import { ModalsProvider } from '@mantine/modals'
import { Notifications } from '@mantine/notifications'
import '@mantine/notifications/styles.css'
import type { Metadata } from 'next'
import { type JSX } from 'react'
import { GoogleApi } from '~/components/google-api'
import { QueryClientWrapper } from '~/components/query-client-wrapper'
import { theme } from '~/lib/theme'

export const metadata: Metadata = {
  title: 'Next.js mail merge',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript defaultColorScheme='light' />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <ModalsProvider>
            <Notifications />
            <QueryClientWrapper>{children}</QueryClientWrapper>
          </ModalsProvider>
        </MantineProvider>
      </body>
      <GoogleApi />
    </html>
  )
}

export default RootLayout
